### ISSUE TITLE
Error when run refresh database command

### ISSUE THREAD

**Issue by TranDucBlog** [sunel/eav#23]
Replay: Run migrate then run migrate: refresh

**Comment by sunel** [comment]
Can you please post the error, no of entities and attributes created

**Comment by TranDucBlog** [comment]
![screenshot from 2018-12-09 10-38-50](https://user-images.githubusercontent.com/26267956/49693195-cd25a100-fb9e-11e8-9cb8-8fc1025b4c48.png)
![screenshot from 2018-12-09 10-39-43](https://user-images.githubusercontent.com/26267956/49693196-cd25a100-fb9e-11e8-8e40-acfe97aa8153.png)

**Comment by sunel** [comment]
@TranDucBlog 

Seeing from the error i suppose it is due to the recent change in the code 

https://github.com/sunel/eav/commit/dda1671a65a8def146bc496b761eec0c8c6fa806

You must have create the attributes before the commit.

All the attribute tables are created in lowercase. in you case product_dateTime -> product_datetime
